abstract: run mech tests by making
author: Hans Dieter Pearcey <hdp@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.57
license: perl
name: Test-WWW-Mechanize-Object
no_index: 
  directory: 
    - inc
    - t
requires: 
  Sub::Exporter: 0
version: 0.01
